theme: jekyll-theme-minimal
logo: assets/logo.png
title: Relatórios e visualização de dados
show_downloads: true
link_material: "https://github.com/curso-r/main-visualizacao/raw/master/material_do_curso.zip"